apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080

